# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='name',
            field=models.CharField(default=website.models.generate_setting_name, max_length=128, verbose_name='Nom de cette configuratino'),
        ),
    ]
