# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 05:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('call_sign', models.CharField(help_text='Unique ship number for an owner', max_length=16)),
                ('length', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='L')),
                ('draft', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='TE')),
                ('helico_observation', models.TextField(blank=True, null=True, verbose_name='Obs hélico')),
                ('helico', models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('quiet_sea_only', 'PMC')], max_length=32, null=True)),
                ('helico_platform_infos', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VesselActivity',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('incomming', 'E'), ('departing', 'S'), ('shifting', 'D')], max_length=16, null=True)),
                ('status', models.CharField(blank=True, choices=[('piloting', 'Piloter'), ('anchoring', 'Mouiller')], max_length=16, null=True)),
                ('good_to_go', models.BooleanField(default=False, verbose_name='BPV')),
                ('incoming_from', models.CharField(blank=True, max_length=128, null=True)),
                ('leaving_to', models.CharField(blank=True, max_length=128, null=True)),
                ('berth', models.CharField(blank=True, max_length=128, null=True, verbose_name='PaQ')),
                ('route', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15')], null=True, verbose_name='RTE')),
                ('sirene_time_estimate', models.DateTimeField(blank=True, null=True)),
                ('sirene_observation', models.TextField(blank=True, null=True, verbose_name='Obs SIRENE')),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('tugs', models.IntegerField(blank=True, null=True)),
                ('services', models.TextField(blank=True, null=True, verbose_name='OP commerciale')),
                ('dangerous_materials', models.IntegerField(blank=True, null=True, verbose_name='Dgx')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vessels.Vessel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
